### ISSUE TITLE
Is this the help drawer component?

### ISSUE THREAD

**Issue by parkerpearson** [Pearson-Higher-Ed/o-drawer#4]
Or is this a more foundational piece the help drawer builds on (similar to the o-header/o-app-header relationship)?

**Comment by aarmour** [comment]
It's a foundational component.

**Comment by parkerpearson** [comment]
Is the help drawer hosted somewhere as an origami component? Or is not
fully compliant with the spec yet?

**Comment by aarmour** [comment]
@parkerpearson Work has not started on the help topics components yet.

**Comment by aarmour** [comment]
@parkerpearson See [o-contextual-help](https://github.com/Pearson-Higher-Ed/o-contextual-help).
